set_property PACKAGE_PIN P4 [get_ports A]
set_property PACKAGE_PIN P3 [get_ports B]
set_property PACKAGE_PIN R3 [get_ports A1]
set_property PACKAGE_PIN T1 [get_ports B1]
set_property PACKAGE_PIN T3 [get_ports S]
set_property PACKAGE_PIN T8 [get_ports Q]